### ISSUE TITLE
wrog NS request at DAD 

### ISSUE THREAD

**Issue by abhiambure** [yarrick/lwip#1]
while performing the DAD process , NS packets sent out should not contain link layer address option. While generation of NS packets link layer address option will be added only if source address is not unspecified address.  

[ns_nd6_patch.txt](https://github.com/yarrick/lwip/files/200016/ns_nd6_patch.txt)

**Comment by yarrick** [comment]
This code is old, please get the latest at http://savannah.nongnu.org/projects/lwip/ and file any issues there.
